version: '2'
services:
  app:
    container_name: cakephp-app
    build: ./app/
    image: cakephp-app
    ports:
      - '80:80'
    volumes:
      - ~/git/github/dev_cakephp4:/var/www/app/
    tty: true
    depends_on:
      - db
  db:
    container_name: cakephp-db
    build: ./mysql/
    image: cakephp-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/db_data:/var/lib/mysql
  redis:
    container_name: cakephp-redis
    image: "redis:latest"
    ports:
      - '6379:6379'
    volumes:
      - ./redis/db_data:/data
